services:
  - type: web
    name: roommate-expense-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: DB_URL
        value: jdbc:postgresql://ep-fancy-glade-axkeli2x-pooler.c-4.us-east-2.aws.neon.tech:5432/neondb?sslmode=require
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        sync: false
      - key: FRONTEND_URL
        value: https://*.vercel.app,http://localhost:5173
      - key: JWT_SECRET
        generateValue: true
